### PR TITLE
chore: init go.mod

### PR DESCRIPTION
**Pull request by haunt98**

### CODE REVIEW

**Comment by sarim** [comment]
@haunt98 If you're interested I can make you a member of the project and we can maintain one single repo instead of two forks.

**Comment by haunt98** [comment]
@sarim Thank you for your invitation. 
I am currently interested in making ibus component engine in Golang so I found out your repo.
There is a lot of new thing for me to learn so I try to make experiment in my repo first before try to make PRs.
If you make me a member of this project, I will make my own fork as playground for testing and send out PRs for you to review :D

**Comment by sarim** [comment]
@haunt98 I invited you. You can experiment on develop branch. Let me know how your input engine experiment goes, sounds like an interesting project :3

**Comment by haunt98** [comment]
Thank you :3 I will update when I get free time outside my work.

**Pull request closed without merging**
